### ISSUE TITLE
Concurrent Move

### ISSUE THREAD

**Issue by ardalis** [CampbellAlexander/GameAI#10]
How does the logic of the AI algorithms change if both players make their moves simultaneously? That would seem to eliminate the need for CurrentPlayer on the interface, for example.

**Comment by ardalis** [comment]
Apparently this is a big topic of recent research...
https://www.google.com/search?q=simultaneous+move+mcts

**Comment by in-op** [comment]
It is. I'm open to new algorithms, but I haven't had time to spend on this library. I'm going to close this because it's too broad, but if there is a _specific_ algorithm you (or anyone reading this) want(s) implemented, don't hesitate to make a new issue, preferably with some links to the algorithm/papers.
